### ISSUE TITLE
can't see the connected device after log in 172.17.8.101

### ISSUE THREAD

**Issue by 442895160** [openstf/setup-examples#3]
Hi,

I followed your setup-examples instructions and all the services are in running state, then I open http://172.17.8.101 and log in stf, but there's no devices showing even my PC is connecting a SAMSUNG phone.

The SAMSUNG phone can be recognized using command "adb devices", also works well in "STF local" environment. I've updated its vendorId and productId in the Vagrantfile which is following your instrunctions.

It looks strange, do you have any idea about this?

**Comment by vbanthia-zz** [comment]
Most probably, the problem is somewhere in the USB filter.

**Things you need to take care**
1. You will have to connect device to your mac before `vagrant up`
2. Do not disconnect device later

**This is how you can debug problem**
1. Once the device is added to VM, you will not see it on your host machine(mac). Your host OS should not show connected device on `adb devices`
2. You can check if the device is connected to VM by below command.

```
vagrant ssh core-01
docker run --rm -ti --net container:adbd sorccu/adb adb devices
```

In case, above command does not show any device, it means there is some problem in VirtualBox USB Filter.

**Comment by 442895160** [comment]
Thanks for your response. I have resolved this problem :)
